version: "3"
services:
  backend:
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    networks:
      - my-network
    volumes:
      - backend-data:/app/backend/data

  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:

volumes:
  backend-data:
# ---------------------------------WORKING------------------------------------

# version: "3"
# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: ./Dockerfile
#     ports:
#       - "3001:3001"

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: ./Dockerfile
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend
# ----------------WORKING-----------------

# version: "3"
# services:
#   surge-assignment-db:
#     image: mongo
#     container_name: "surge-assignment-db"
#     ports:
#       - 27017:27017
#     networks:
#       - fullstack
#   surge-assignment-app:
#     build: .
#     container_name: "surge-assignment-app"
#     restart: always
#     ports:
#       - 3000:3000
#       - 4001:4001
#     environment:
#       - MONGODB_URL=mongodb://surge-assignment-db:27017
#       - NODE_ENV=prod
#       - FRONTEND_HOST=http://localhost:3001/
#     networks:
#       - fullstack

# networks:
#   fullstack:
#     driver: bridge
