"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { ShopContextProvider } from "@/context/show-context";
import SideBar from "@/components/SideBar";
import { usePathname } from "next/navigation";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathName = usePathname();

  console.log(pathName);
  return (
    <html lang="en">
      <body className={inter.className}>
        <ShopContextProvider>
          {pathName != "/users/login" && pathName != "/users/signup" && (
            <NavBar />
          )}
          {/* <SideBar>{children}</SideBar> */}

          {children}

          <Footer />
        </ShopContextProvider>
      </body>
    </html>
  );
}
